# Generated by Django 2.2.3 on 2019-07-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kottayamhosters', '0002_add_logo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description_logo', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploaded_pictures/photo')),
            ],
        ),
        migrations.CreateModel(
            name='Add_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description_logo', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploaded_pictures/photo')),
            ],
        ),
    ]
