# Generated by Django 2.2.3 on 2019-08-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kottayamhosters', '0004_auto_20190726_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_printart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=250)),
                ('design_description_logo', models.TextField(blank=True, null=True)),
                ('design_photo', models.ImageField(blank=True, null=True, upload_to='uploaded_pictures/photo')),
            ],
        ),
    ]
