# Generated by Django 2.2.3 on 2019-08-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kottayamhosters', '0005_add_printart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_printart',
            old_name='design_description_logo',
            new_name='printart_description_logo',
        ),
        migrations.RenameField(
            model_name='add_printart',
            old_name='design_name',
            new_name='printart_name',
        ),
        migrations.RenameField(
            model_name='add_printart',
            old_name='design_photo',
            new_name='printart_photo',
        ),
    ]
